# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-16 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='last_location',
            field=models.CharField(default='Union 525, Indianapolis, IN', max_length=1028),
            preserve_default=False,
        ),
    ]
