# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-16 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('profile', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='FoodItemClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=512)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.Business')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualFoodItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'Available'), ('2', 'Requested'), ('3', 'PickedUp'), ('4', 'Delivered')], max_length=50)),
                ('item_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.FoodItemClass')),
            ],
        ),
    ]
