# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-16 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualfooditem',
            name='status',
            field=models.CharField(choices=[('1', 'Available'), ('2', 'Requested')], max_length=50),
        ),
    ]
