# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-16 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_auto_20180616_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditemclass',
            name='carbs',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='fooditemclass',
            name='fat',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='fooditemclass',
            name='protein',
            field=models.IntegerField(default=None),
        ),
    ]
