# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-16 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_auto_20180616_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditemclass',
            name='calories',
            field=models.IntegerField(default=None),
        ),
    ]
