# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-16 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0007_auto_20180616_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditemclass',
            name='calories',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
