# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-16 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0008_auto_20180616_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditemclass',
            name='calories',
        ),
    ]
