# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-16 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0009_remove_fooditemclass_calories'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditemclass',
            name='calories',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
