# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-16 19:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('businesses', '0001_initial'),
        ('volunteers', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_running', models.BooleanField(default=False)),
                ('status', models.CharField(default='1', max_length=50)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.Business')),
                ('items', models.ManyToManyField(related_name='requestfooditems', to='businesses.IndividualFoodItem')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=256)),
                ('gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female')], max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('cart', models.ManyToManyField(related_name='cart', to='businesses.IndividualFoodItem')),
                ('profile', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='PickupRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='1', max_length=50)),
                ('date_created', models.DateTimeField()),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='volunteers.Volunteer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('calories', models.IntegerField(default=0)),
                ('carbohydrates', models.IntegerField(default=0)),
                ('proteins', models.IntegerField(default=0)),
                ('fat', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
        ),
        migrations.AddField(
            model_name='businessrequest',
            name='parentRequest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_set', to='clients.PickupRequest'),
        ),
    ]
