# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-16 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='active',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('1', 'Male'), ('2', 'Female')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='businessrequest',
            name='status',
            field=models.CharField(default='Requested', max_length=50),
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='status',
            field=models.CharField(default='1', max_length=50),
        ),
    ]
