# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-16 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessrequest',
            name='status',
            field=models.CharField(default=b'1', max_length=50),
        ),
    ]
