# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-16 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_auto_20180616_1625'),
        ('clients', '0002_pickuprequest_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_running', models.BooleanField(default=False)),
                ('status', models.CharField(default='Requested', max_length=50)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.Business')),
                ('items', models.ManyToManyField(related_name='requestfooditems', to='businesses.IndividualFoodItem')),
                ('parentRequest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.IndividualFoodItem')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('calories', models.IntegerField(default=0)),
                ('carbohydrates', models.IntegerField(default=0)),
                ('proteins', models.IntegerField(default=0)),
                ('fat', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
        ),
        migrations.RemoveField(
            model_name='pickuprequest',
            name='items',
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='status',
            field=models.CharField(default='1', max_length=50),
        ),
    ]
