# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-16 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20180616_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessrequest',
            name='parentRequest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.PickupRequest'),
        ),
    ]
