# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-16 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='member_type',
            field=models.CharField(choices=[('1', 'Senior Citizen'), ('2', 'Volunteer Driver'), ('3', 'Restaurant')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='timezone',
            field=models.CharField(default='EST', max_length=50),
        ),
    ]
